#! /bin/sh

cd local/templates

for f in $(find . -name '*.dust'); do
  NAME=`echo $f | sed -e 's,\.dust,,' | sed -e 's,\./,,'`
  TPL="../../public/scripts/templates/`echo $f | sed -e 's,\.dust,\.js,'`"
  echo "var dust = require('../dust-core.min.js');" > $TPL
  dustc --name=$NAME $f >> $TPL
done

cd ../..

browserify "public/scripts/main.js" -o "public/scripts/bundle.js"
